services:
  - type: web
    name: lms-socket-server
    env: node
    plan: free
    region: oregon
    branch: feature/lobby-code-ui
    buildCommand: npm install
    startCommand: npm run ws-server
    envVars:
      - key: PORT
        value: "3000"
    healthCheckPath: /
    autoDeploy: true
